name: Deploy Laravel App

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create GitHub Release"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

    version:
      description: "Release version (e.g. v1.0.0)"
      required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # install rsync
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install rsync

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql
          tools: composer

      # Install Composer dependencies (optimized for production)
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Build frontend (if applicable)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build assets
        run: |
          npm ci
          npm run build
        if: hashFiles('package.json') != ''

      # Cleaning up package
      - name: Prepare deployment package
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .git .github .editorconfig
          rm -f .env README.md .gitignore

       # Create tarball
      - name: Create tar archive
        env:
          VERSION: ${{ inputs.version }}
        run: |
          if [ -z "$VERSION" ]; then
            VERSION="dev"
          fi
          TAR_NAME="secret-app-$VERSION.tar.gz"
          tar -czf "$TAR_NAME" .
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV

      # Create GitHub Release (optional)
      - name: Create GitHub Release
        if: inputs.create_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Secret App ${{ inputs.version }}
          draft: false
          prerelease: false
          files: |
            ${{ env.TAR_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}