name: Deploy Laravel App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # install rsync
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install rsync

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql
          tools: composer

      # Install Composer dependencies (optimized for production)
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Build frontend (if applicable)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build assets
        run: |
          npm ci
          npm run build
        if: hashFiles('package.json') != ''

      # Prepare deployment package
      - name: Prepare deployment package
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .git .github
          rm -f .env README.md

      # Deploy to VPS
      - name: Setting up Environment
        run: |
          # create env from secret (token, id, public key)
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
           rsync -aAXvhP -e  "ssh -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}
        # uses: burnett01/rsync-deployments@7.1.0
        # with:
        #   switches: -avzr --delete --exclude='.env' --exclude='storage/' -e "ssh -p {{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no" --rsync-path="echo '${{ secrets.VPS_PW }}' | sudo -S rsync" 
        #   path: ./
        #   remote_path: ${{ secrets.VPS_PATH }} # path to your vps
        #   remote_host: ${{ secrets.VPS_HOST }} # the host or server IP
        #   remote_port: ${{ secrets.VPS_PORT }} # the port 
        #   remote_user: ${{ secrets.VPS_USER }} # the user (recommend to use root)
        #   remote_key: ${{ secrets.VPS_KEY }} #the private ssh key
        #   # https://github.com/Burnett01/rsync-deployments